
import jaco.mp3.player.MP3Player;
import java.io.File;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Level1_Opposite extends javax.swing.JFrame {

    /**
     * Creates new form Level1_Opposite
     */
    public Level1_Opposite() {
        initComponents();
        jRadioButton1.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton3.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton5.setVisible(true);
        jRadioButton7.setVisible(false);
        jRadioButton8.setVisible(false);
        jRadioButton9.setVisible(false);
        jRadioButton10.setVisible(false);
        jRadioButton11.setVisible(false);
        jRadioButton12.setVisible(false);
        jRadioButton13.setVisible(false);
        jRadioButton14.setVisible(false);
        jRadioButton15.setVisible(false);
        jRadioButton16.setVisible(false);
        jRadioButton17.setVisible(false);
        jRadioButton18.setVisible(false);
        jRadioButton19.setVisible(false);
        jRadioButton20.setVisible(false);
        jRadioButton21.setVisible(true);
        jRadioButton22.setVisible(false);
        jRadioButton23.setVisible(false);
        jRadioButton24.setVisible(false);
        jRadioButton25.setVisible(false);
        jRadioButton26.setVisible(false);
        jRadioButton27.setVisible(false);
        jRadioButton28.setVisible(false);
        jRadioButton29.setVisible(false);
        jRadioButton30.setVisible(false);
        jRadioButton31.setVisible(true);
        jRadioButton32.setVisible(false);
        jRadioButton33.setVisible(false);
        jRadioButton34.setVisible(true);
        jRadioButton35.setVisible(false);   
        jRadioButton36.setVisible(false);
        jRadioButton37.setVisible(false);
        jRadioButton38.setVisible(false);
        jRadioButton39.setVisible(false);
        jRadioButton40.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jButton10.setVisible(false);
        jButton11.setVisible(false);
        jButton14.setVisible(false);
     
    }
static int count=0,score=0,l=0;
public static final String SONG="D:\\Dipti\\KidsLearningSystem\\Audio file\\Correct-Answer-3-Sound-Effect_0ZQ-Lk--ILE.mp3";
MP3Player mp3player=new MP3Player(new File(SONG));
public static final String Song2="D:\\Dipti\\KidsLearningSystem\\Audio file\\Game-Over-Sound-Effect-HD_NN_8vfN0HP4.mp3";
MP3Player mp3player2=new MP3Player(new File(Song2));
public static final String Song3="D:\\Dipti\\KidsLearningSystem\\Audio file\\Buzzer-Wrong-Answer-Gaming-Sound-Effect-HD_FRpq7o1mKXY.mp3";
MP3Player mp3player3=new MP3Player(new File(Song3));
public static final String SONG4="D:\\Dipti\\KidsLearningSystem\\Audio file\\Mouse-Click-Sound-Effect-HD_h6_8SlZZwvQ.mp3";
MP3Player mp3player4=new MP3Player(new File(SONG4));


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton1.setText("Worst");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton3.setText("Short");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton4.setText("Little");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton5.setText("Gone");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Q1. What is the opposite of Go ?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 650, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 0));
        jLabel2.setText("Answer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 206, 23));
        jLabel3.setText("_____________________");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 320, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 0));
        jLabel7.setText("00");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 0));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 300, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 60));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 60));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 60));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 60));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 60));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 60));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 60));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 60));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 60));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chck.png"))); // NOI18N
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 0));
        jLabel5.setText("Score ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 0));
        jLabel6.setText("00");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 0));
        jLabel8.setText("/");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton2.setText("Hate");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton6.setText("Worse");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton7.setText("Sweet");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jRadioButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton8.setText("Lie");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jRadioButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton9.setText("False");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jRadioButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton10.setText("Correct");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jRadioButton11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton11.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton11.setText("Well");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jRadioButton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton12.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton12.setText("Easy");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jRadioButton13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton13.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton13.setText("Simple");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jRadioButton14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton14.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton14.setText("Tall");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jRadioButton15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton15.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton15.setText("Small");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jRadioButton16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton16.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton16.setText("Hard");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jRadioButton17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton17.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton17.setText("Heavy");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jRadioButton18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton18.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton18.setText("Clean");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jRadioButton19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton19.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton19.setText("Safe");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jRadioButton20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton20.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton20.setText("Spotless");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jRadioButton21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton21.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton21.setText("Went");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jRadioButton22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton22.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton22.setText("Dusty");
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jRadioButton23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton23.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton23.setText("Affection");
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jRadioButton24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton24.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton24.setText("No");
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jRadioButton25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton25.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton25.setText("Bellow");
        jRadioButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jRadioButton26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton26.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton26.setText("Behind");
        jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jRadioButton27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton27.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton27.setText("Over");
        jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jRadioButton28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton28.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton28.setText("In front ");
        jRadioButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jRadioButton29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton29.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton29.setText("Before");
        jRadioButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jRadioButton30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton30.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton30.setText("Late");
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jRadioButton31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton31.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton31.setText("Come");
        jRadioButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jRadioButton32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton32.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton32.setText("Bad");
        jRadioButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jRadioButton33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton33.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton33.setText("Angry");
        jRadioButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jRadioButton34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton34.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton34.setText("Came");
        jRadioButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton34ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jRadioButton35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton35.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton35.setText("Descent");
        jRadioButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton35ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jRadioButton36.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton36.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton36.setText("Old");
        jRadioButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jRadioButton37.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton37.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton37.setText("Previous");
        jRadioButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton37ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jRadioButton38.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton38.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton38.setText("Before");
        jRadioButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton38ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jRadioButton39.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton39.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton39.setText("First");
        jRadioButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton39ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jRadioButton40.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton40.setForeground(new java.awt.Color(204, 255, 0));
        jRadioButton40.setText("Previous");
        jRadioButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton40ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3D-Red-Heart-Image.png"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 50, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3D-Red-Heart-Image.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 50, 40));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3D-Red-Heart-Image.png"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 50, 40));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PRE.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, -1));

        jLabel9.setForeground(new java.awt.Color(255, 0, 153));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LVE     L1OPBG.jpg"))); // NOI18N
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 5, true));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Worst");
        }
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Little");
        }
       
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String s1=jLabel4.getText();
         count=count+1;
        if(s1.equals("Bad")){    
            mp3player.play();
            score=score+1;
            jLabel6.setText(String.valueOf(score));
            jLabel7.setText(String.valueOf(count));
            jRadioButton2.setVisible(true);
            jRadioButton11.setVisible(false);
            jRadioButton23.setVisible(true);
            jRadioButton33.setVisible(true);
            jRadioButton7.setVisible(true);
            jRadioButton1.setVisible(false);
            jRadioButton6.setVisible(false);
            jRadioButton32.setVisible(false);
            
            jLabel1.setText("Q2. What is the opposite of Love ?");


        }
        else{
            mp3player3.play();
            l=l+1;
            if(l==1){
                jLabel23.setVisible(false);   
            }
            else{
                if(l==2){
                    jLabel22.setVisible(false);
                }
                else{
                    if(l==3){
                        jLabel21.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Your Score is "+score);
            new OppositeGameOver().setVisible(true);
            setVisible(false);
            mp3player2.play();
                    }
                }
            }
            jLabel7.setText(String.valueOf(count));
            jRadioButton2.setVisible(true);
            jRadioButton11.setVisible(false);
            jRadioButton23.setVisible(true);
            jRadioButton33.setVisible(true);
            jRadioButton7.setVisible(true);
            jRadioButton1.setVisible(false);
            jRadioButton6.setVisible(false);
            jRadioButton32.setVisible(false);
            
            jLabel1.setText("Q2. What is the opposite of Love ?");
        }
            jButton3.setVisible(false);
            jButton4.setVisible(true);
            jLabel4.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s1=jLabel4.getText();
         count=count+1;
        if(s1.equals("Come")){  
             mp3player.play();
            score=score+1;
            jLabel6.setText(String.valueOf(score));
            jLabel7.setText(String.valueOf(count));
            jRadioButton34.setVisible(false);
            jRadioButton31.setVisible(false);
            jRadioButton21.setVisible(false);
            jRadioButton5.setVisible(false);
            jRadioButton4.setVisible(true);
            jRadioButton14.setVisible(true);
            jRadioButton15.setVisible(true);
            jRadioButton3.setVisible(true);
            
            jLabel1.setText("Q2. What is the opposite of Big ?");


        }
        else{
             mp3player3.play();
            l=l+1;
            if(l==1){
                jLabel23.setVisible(false);   
            }
            else{
                if(l==2){
                    jLabel22.setVisible(false);
                }
                else{
                    if(l==3){
                        jLabel21.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Your Score is "+score);
            new OppositeGameOver().setVisible(true);
            setVisible(false);
            mp3player2.play();
                    }
                }
            }
            jLabel7.setText(String.valueOf(count));
             jRadioButton34.setVisible(false);
            jRadioButton31.setVisible(false);
            jRadioButton21.setVisible(false);
            jRadioButton5.setVisible(false);
            jRadioButton4.setVisible(true);
            jRadioButton14.setVisible(true);
            jRadioButton15.setVisible(true);
            jRadioButton3.setVisible(true);
            
            jLabel1.setText("Q2. What is the opposite of Big ?");
            
        }
            jButton1.setVisible(false);
            jButton2.setVisible(true);
            jLabel4.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jLabel4.setText("Short");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        jLabel4.setText("Gone");
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
              jLabel4.setText("Hate");
          }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
          if(jLabel4.getText().isEmpty()){
              jLabel4.setText("Worse");
          }
        
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
          if(jLabel4.getText().isEmpty()){
              jLabel4.setText("Sweet");
          }
         
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
          if(jLabel4.getText().isEmpty()){
              
              jLabel4.setText("Lie");
          
          }
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
          if(jLabel4.getText().isEmpty()){
              
              jLabel4.setText("False");
          
          }
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
          if(jLabel4.getText().isEmpty()){
             
              jLabel4.setText("Correct");
          
          }
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
          if(jLabel4.getText().isEmpty()){
               jLabel4.setText("Well");
          }
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
          if(jLabel4.getText().isEmpty()){
               jLabel4.setText("Easy");
          }
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
          if(jLabel4.getText().isEmpty()){
               jLabel4.setText("Simple");
          }
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
         if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Tall");
         }
         
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:
         
         if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Small");
         }
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // TODO add your handling code here:
       
         if(jLabel4.getText().isEmpty()){
               jLabel4.setText("Hard");
         }
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Heavy");
        }
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Clean");
        }
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Safe");
        }
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Spotless");
        }
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
            jLabel4.setText("Went");
        }
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Dusty");
        }
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
            jLabel4.setText("Affection");
        }
         
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
            jLabel4.setText("No");
        }
         
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    private void jRadioButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton25ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Bellow");
        }
        
    }//GEN-LAST:event_jRadioButton25ActionPerformed

    private void jRadioButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton26ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Behind");
        }
    }//GEN-LAST:event_jRadioButton26ActionPerformed

    private void jRadioButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton27ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Over");
        }
    }//GEN-LAST:event_jRadioButton27ActionPerformed

    private void jRadioButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton28ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("In front");
        }
    }//GEN-LAST:event_jRadioButton28ActionPerformed

    private void jRadioButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton29ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Before");
        }
    }//GEN-LAST:event_jRadioButton29ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Late");
        }
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void jRadioButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton31ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Come");
        }
    }//GEN-LAST:event_jRadioButton31ActionPerformed

    private void jRadioButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton32ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
            jLabel4.setText("Bad");
        }
    }//GEN-LAST:event_jRadioButton32ActionPerformed

    private void jRadioButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton33ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
         jLabel4.setText("Angry");
        }
    }//GEN-LAST:event_jRadioButton33ActionPerformed

    private void jRadioButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton34ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Came");
        }
        
    }//GEN-LAST:event_jRadioButton34ActionPerformed

    private void jRadioButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton35ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Descent");
        }
    }//GEN-LAST:event_jRadioButton35ActionPerformed

    private void jRadioButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton36ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Old");
        }
    }//GEN-LAST:event_jRadioButton36ActionPerformed

    private void jRadioButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton37ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Previous");
        }
    }//GEN-LAST:event_jRadioButton37ActionPerformed

    private void jRadioButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton38ActionPerformed
        // TODO add your handling code here:
      if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Before");
        }
    }//GEN-LAST:event_jRadioButton38ActionPerformed

    private void jRadioButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton39ActionPerformed
        // TODO add your handling code here:
         jLabel4.setText("First");
    }//GEN-LAST:event_jRadioButton39ActionPerformed

    private void jRadioButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton40ActionPerformed
        // TODO add your handling code here:
        if(jLabel4.getText().isEmpty()){
             jLabel4.setText("Previous");
        }
    }//GEN-LAST:event_jRadioButton40ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String s1=jLabel4.getText();
         count=count+1;
        if(s1.equals("Small")){   
             mp3player.play();
            score=score+1;
            jLabel6.setText(String.valueOf(score));
            jLabel7.setText(String.valueOf(count));
            jRadioButton4.setVisible(false);
            jRadioButton14.setVisible(false);
            jRadioButton15.setVisible(false);
            jRadioButton3.setVisible(false);
            jRadioButton6.setVisible(true);
            jRadioButton1.setVisible(true);
            jRadioButton11.setVisible(true);
            jRadioButton32.setVisible(true);
            
            jLabel1.setText("Q2. What is the opposite of Good ?");


        }
        else{
             mp3player3.play();
            l=l+1;
            if(l==1){
                jLabel23.setVisible(false);   
            }
            else{
                if(l==2){
                    jLabel22.setVisible(false);
                }
                else{
                    if(l==3){
                        jLabel21.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Your Score is "+score);
            new OppositeGameOver().setVisible(true);
            setVisible(false);
            mp3player2.play();
                    }
                }
            }
            jLabel7.setText(String.valueOf(count));
            jRadioButton4.setVisible(false);
            jRadioButton14.setVisible(false);
            jRadioButton15.setVisible(false);
            jRadioButton3.setVisible(false);
            jRadioButton6.setVisible(true);
            jRadioButton1.setVisible(true);
            jRadioButton11.setVisible(true);
            jRadioButton32.setVisible(true);
            
            jLabel1.setText("Q2. What is the opposite of Good ?");
            
        }
            jButton2.setVisible(false);
            jButton3.setVisible(true);
         jLabel4.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String s1=jLabel4.getText();
         count=count+1;
        if(s1.equals("Hate")){     
             mp3player.play();
            score=score+1;
            jLabel6.setText(String.valueOf(score));
            jLabel7.setText(String.valueOf(count));
            jRadioButton23.setVisible(false);
            jRadioButton33.setVisible(false);
            jRadioButton2.setVisible(false);
            jRadioButton7.setVisible(false);
            jRadioButton8.setVisible(true);
            jRadioButton9.setVisible(true);
            jRadioButton10.setVisible(true);
            jRadioButton24.setVisible(true);
            jLabel1.setText("Q2. What is the opposite of True ?");
        }
        else{
             mp3player3.play();
            l=l+1;
            if(l==1){
                jLabel23.setVisible(false);   
            }
            else{
                if(l==2){
                    jLabel22.setVisible(false);
                }
                else{
                    if(l==3){
                        jLabel21.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Your Score is "+score);
            new OppositeGameOver().setVisible(true);
            setVisible(false);
            mp3player2.play();
                    }
                }
            }
            jLabel7.setText(String.valueOf(count));
             jRadioButton23.setVisible(false);
            jRadioButton33.setVisible(false);
            jRadioButton2.setVisible(false);
            jRadioButton7.setVisible(false);
            jRadioButton8.setVisible(true);
            jRadioButton9.setVisible(true);
            jRadioButton10.setVisible(true);
            jRadioButton24.setVisible(true);
            jLabel1.setText("Q2. What is the opposite of True ?");
        }
            jButton4.setVisible(false);
            jButton5.setVisible(true);
             jLabel4.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String s1=jLabel4.getText();
         count=count+1;
        if(s1.equals("False")){   
             mp3player.play();
            score=score+1;
            jLabel6.setText(String.valueOf(score));
            jLabel7.setText(String.valueOf(count));
            jRadioButton8.setVisible(false);
            jRadioButton9.setVisible(false);
            jRadioButton10.setVisible(false);
            jRadioButton24.setVisible(false);
            jRadioButton12.setVisible(true);
            jRadioButton13.setVisible(true);
            jRadioButton16.setVisible(true);
            jRadioButton17.setVisible(true);
            jLabel1.setText("Q2. What is the opposite of Difficult ?");


        }
        else{
             mp3player3.play();
            l=l+1;
            if(l==1){
                jLabel23.setVisible(false);   
            }
            else{
                if(l==2){
                    jLabel22.setVisible(false);
                }
                else{
                    if(l==3){
                        jLabel21.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Your Score is "+score);
            new OppositeGameOver().setVisible(true);
            setVisible(false);
            mp3player2.play();
                    }
                }
            }
            jLabel7.setText(String.valueOf(count));
             jRadioButton8.setVisible(false);
            jRadioButton9.setVisible(false);
            jRadioButton10.setVisible(false);
            jRadioButton24.setVisible(false);
            jRadioButton12.setVisible(true);
            jRadioButton13.setVisible(true);
            jRadioButton16.setVisible(true);
            jRadioButton17.setVisible(true);
            jLabel1.setText("Q2. What is the opposite of Difficult ?");
        }
            jButton5.setVisible(false);
            jButton6.setVisible(true);
             jLabel4.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        String s1=jLabel4.getText();
         count=count+1;
        if(s1.equals("Easy")){    
             mp3player.play();
            score=score+1;
            jLabel6.setText(String.valueOf(score));
            jLabel7.setText(String.valueOf(count));
            jRadioButton12.setVisible(false);
            jRadioButton13.setVisible(false);
            jRadioButton16.setVisible(false);
            jRadioButton17.setVisible(false);
            jRadioButton18.setVisible(true);
            jRadioButton19.setVisible(true);
            jRadioButton20.setVisible(true);
            jRadioButton22.setVisible(true);
            jLabel1.setText("Q2. What is the opposite of Dirty ?");


        }
        else{
             mp3player3.play();
            l=l+1;
            if(l==1){
                jLabel23.setVisible(false);   
            }
            else{
                if(l==2){
                    jLabel22.setVisible(false);
                }
                else{
                    if(l==3){
                        jLabel21.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Your Score is "+score);
            new OppositeGameOver().setVisible(true);
            setVisible(false);
            mp3player2.play();
                    }
                }
            }
             jLabel7.setText(String.valueOf(count));
            jRadioButton12.setVisible(false);
            jRadioButton13.setVisible(false);
            jRadioButton16.setVisible(false);
            jRadioButton17.setVisible(false);
            jRadioButton18.setVisible(true);
            jRadioButton19.setVisible(true);
            jRadioButton20.setVisible(true);
            jRadioButton22.setVisible(true);
            jLabel1.setText("Q2. What is the opposite of Dirty ?");
        }
            jButton6.setVisible(false);
            jButton7.setVisible(true);
             jLabel4.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String s1=jLabel4.getText();
         count=count+1;
        if(s1.equals("Clean")){    
             mp3player.play();
            score=score+1;
            jLabel6.setText(String.valueOf(score));
            jLabel7.setText(String.valueOf(count));
            jRadioButton18.setVisible(false);
            jRadioButton19.setVisible(false);
            jRadioButton20.setVisible(false);
            jRadioButton22.setVisible(false);
            jRadioButton25.setVisible(true);
            jRadioButton26.setVisible(true);
            jRadioButton27.setVisible(true);
            jRadioButton28.setVisible(true);
            jLabel1.setText("Q2. What is the opposite of Above ?");


        }
        else{
             mp3player3.play();
            l=l+1;
            if(l==1){
                jLabel23.setVisible(false);   
            }
            else{
                if(l==2){
                    jLabel22.setVisible(false);
                }
                else{
                    if(l==3){
                        jLabel21.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Your Score is "+score);
            new OppositeGameOver().setVisible(true);
            setVisible(false);
            mp3player2.play();
                    }
                }
            }
            jLabel7.setText(String.valueOf(count));
            jRadioButton18.setVisible(false);
            jRadioButton19.setVisible(false);
            jRadioButton20.setVisible(false);
            jRadioButton22.setVisible(false);
            jRadioButton25.setVisible(true);
            jRadioButton26.setVisible(true);
            jRadioButton27.setVisible(true);
            jRadioButton28.setVisible(true);
            jLabel1.setText("Q2. What is the opposite of Above ?");
        }
            jButton7.setVisible(false);
            jButton8.setVisible(true);
             jLabel4.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         String s1=jLabel4.getText();
         count=count+1;
        if(s1.equals("Bellow")){  
             mp3player.play();
            score=score+1;
            jLabel6.setText(String.valueOf(score));
            jLabel7.setText(String.valueOf(count));
            jRadioButton25.setVisible(false);
            jRadioButton26.setVisible(false);
            jRadioButton27.setVisible(false);
            jRadioButton28.setVisible(false);
            jRadioButton29.setVisible(true);
            jRadioButton30.setVisible(true);
            jRadioButton39.setVisible(true);
            jRadioButton40.setVisible(true);
            jLabel1.setText("Q2. What is the opposite of After ?");


        }
        else{
             mp3player3.play();
            l=l+1;
            if(l==1){
                jLabel23.setVisible(false);   
            }
            else{
                if(l==2){
                    jLabel22.setVisible(false);
                }
                else{
                    if(l==3){
                        jLabel21.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Your Score is "+score);
            new OppositeGameOver().setVisible(true);
            setVisible(false);
            mp3player2.play();
                    }
                }
            }
            jLabel7.setText(String.valueOf(count));
            jRadioButton25.setVisible(false);
            jRadioButton26.setVisible(false);
            jRadioButton27.setVisible(false);
            jRadioButton28.setVisible(false);
            jRadioButton29.setVisible(true);
            jRadioButton30.setVisible(true);
            jRadioButton39.setVisible(true);
            jRadioButton40.setVisible(true);
            jLabel1.setText("Q2. What is the opposite of After ?");
        }
            jButton8.setVisible(false);
            jButton10.setVisible(true);
             jLabel4.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String s1=jLabel4.getText();
         count=count+1;
        if(s1.equals("Before")){    
             mp3player.play();
            score=score+1;
            jLabel6.setText(String.valueOf(score));
            jLabel7.setText(String.valueOf(count));
            jRadioButton29.setVisible(false);
            jRadioButton30.setVisible(false);
            jRadioButton39.setVisible(false);
            jRadioButton40.setVisible(false);
            jRadioButton35.setVisible(true);
            jRadioButton36.setVisible(true);
            jRadioButton37.setVisible(true);
            jRadioButton38.setVisible(true);
            jLabel1.setText("Q2. What is the opposite of Ascent ?");

        }
        else{
             mp3player3.play();
            l=l+1;
            if(l==1){
                jLabel23.setVisible(false);   
            }
            else{
                if(l==2){
                    jLabel22.setVisible(false);
                }
                else{
                    if(l==3){
                        jLabel21.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Your Score is "+score);
            new OppositeGameOver().setVisible(true);
            setVisible(false);
            mp3player2.play();
                    }
                }
            }
            jLabel7.setText(String.valueOf(count));
           jRadioButton29.setVisible(false);
            jRadioButton30.setVisible(false);
            jRadioButton39.setVisible(false);
            jRadioButton40.setVisible(false);
            jRadioButton35.setVisible(true);
            jRadioButton36.setVisible(true);
            jRadioButton37.setVisible(true);
            jRadioButton38.setVisible(true);
            jLabel1.setText("Q2. What is the opposite of Ascent ?");
        }
            jButton10.setVisible(false);
            jButton11.setVisible(true);
             jLabel4.setText("");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String s1=jLabel4.getText();
        count=count+1;
        if(s1.equals("Descent")){
             mp3player.play();
            score=score+1;
            jLabel6.setText(String.valueOf(score));
            jLabel7.setText(String.valueOf(count));
            JOptionPane.showMessageDialog(null, "Your Score is "+score);
            new OppositeGameOver().setVisible(true);
        }
        else{
             mp3player3.play();
            l=l+1;
            if(l==1){
                jLabel23.setVisible(false);   
            }
            else{
                if(l==2){
                    jLabel22.setVisible(false);
                }
                else{
                    if(l==3){
                        jLabel21.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Your Score is "+score);
            new OppositeGameOver().setVisible(true);
            setVisible(false);
            mp3player2.play();
                    }
                }
            }
            JOptionPane.showMessageDialog(null, "Your Score is "+score);
            new OppositeGameOver().setVisible(true);
            setVisible(false);
            mp3player2.play();

        }

        jLabel4.setText("");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        mp3player4.play();
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to stop playing","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {           
            new Opposite().setVisible(true);
             setVisible(false);
        }
       
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level1_Opposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level1_Opposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level1_Opposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level1_Opposite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level1_Opposite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
